source 'https://rubygems.org'
require_relative 'gem_package_dependencies'

#################################### Section ############################################

# gem_package_dependencies brew: ['cmake'], yum: ['cmake'], pacman: ['cmake']
# gem 'rugged'

gem_package_dependencies brew: ['libxml2', 'libxslt']
gem 'nokogiri'

gem 'ru'
gem 'awesome_print'
gem 'activesupport'
gem 'chef-sugar'
gem 'hashdiff'
gem 'CFPropertyList'
gem 'lps'
gem 'xml-simple'
gem 'jenkins_api_client'
gem 'aws-sdk'
gem 'chefspec'
gem 'knife-solo_data_bag'
gem 'mixlib-cli'
gem 'pry'
gem 'addressable'
gem 'facets'
gem 'httparty'
gem 'rake'
gem 'sshkey'
gem 'json'
gem 'nexus_cli', '= 4.1.0.2'
gem 'mixlib-shellout'
gem 'elasticsearch'
gem 'deep_merge'
gem 'cucumber'
gem 'rspec'
gem 'selenium-webdriver'

gem 'cfndsl'
gem 'cfn2dsl', '= 0.1.5'

#################################### VAGRANT ############################################
#                                Vagrant Plugins

group :plugins do
  gem 'vagrant-aws'
  gem 'vagrant-winrm'
  gem 'vagrant-aws-winrm'
  gem 'vagrant-triggers'
end

gem 'macaddr', '= 1.8.7'
gem 'fog-core', '= 1.43.0'

#################################### VAGRANT ############################################

gem 'berkshelf',              '~> 4.3.5', {'type' => :development}

gem 'wdm',                    '0.1.1.1', {'type' => :development}
gem 'winrm',                  '~> 1.6', {'type' => :development}
gem 'winrm-fs',               '~> 0.3.0', {'type' => :development}

gem 'vagrant',                '= 1.8.4', {'type' => :development}

#################################### CHEF ############################################


gem 'chef',                   '= 12.9.38', {'type' => :development}
gem 'hashie', '= 3.4.6'

platforms :mingw do
  gem 'win32-api',      '~> 1.5.3', {'type' => :development}
  gem 'win32-dir',      '~> 0.5.0', {'type' => :development}
  gem 'win32-event',    '~> 0.6.1', {'type' => :development}
  gem 'win32-eventlog', '= 0.6.3', {'type' => :development}
  gem 'win32-mmap',     '~> 0.4.1', {'type' => :development}
  gem 'win32-mutex',    '~> 0.4.2', {'type' => :development}
  gem 'win32-process',  '~> 0.8.2', {'type' => :development}
  gem 'win32-service',  '~> 0.8.7', {'type' => :development}
  gem 'windows-api',    '~> 0.4.4', {'type' => :development}
  gem 'wmi-lite',       '~> 1.0', {'type' => :development}
end
